-- Current Date CURDATE()
SELECT 
  title AS MovieName, 
  CURDATE() AS CurrentDate
FROM film;

-- CURRENT_DATE =>  YYYY-MM-DD
SELECT CURRENT_DATE();

-- CURRENT_TIME =>  HH:MM:SS
SELECT CURRENT_TIME();

-- CURTIME => HH:MM:SS
SELECT CURTIME();

-- CURRENT_TIMESTAMP() => YYYY-MM-DD HH:MM:SS
SELECT CURRENT_TIMESTAMP();

