-- Current Date CURDATE()
SELECT 
  title AS MovieName, 
  CURDATE() AS CurrentDate
FROM film;

-- CURRENT_DATE =>  YYYY-MM-DD
SELECT CURRENT_DATE();

-- CURRENT_TIME =>  HH:MM:SS
SELECT CURRENT_TIME();

-- CURTIME => HH:MM:SS
SELECT CURTIME();

-- CURRENT_TIMESTAMP() => YYYY-MM-DD HH:MM:SS
SELECT CURRENT_TIMESTAMP();


-- MYSQL time intervals
-- MICROSECOND
-- SECOND
-- MINUTE
-- HOUR
-- DAY
-- WEEK
-- MONTH
-- QUARTER
-- YEAR
-- SECOND_MICROSECOND
-- MINUTE_MICROSECOND
-- MINUTE_SECOND
-- HOUR_MICROSECOND
-- HOUR_SECOND
-- HOUR_MINUTE
-- DAY_MICROSECOND
-- DAY_SECOND
-- DAY_MINUTE
-- DAY_HOUR
-- YEAR_MONTH

-- ADDDATE(YYYY-MM-DD, INTERVAL NN INTERVAL) 
SELECT ADDDATE("2022-11-26", INTERVAL 10 DAY);

-- ADDDATE(CURDATE(), INTERVAL NN INTERVAL) 
SELECT ADDDATE(CURDATE(), INTERVAL 10 DAY);
SELECT ADDDATE(CURDATE(), INTERVAL 1 MONTH);


-- ADDDATE(CURDATE(), INTERVAL -NN INTERVAL) 
SELECT ADDDATE(CURDATE(), INTERVAL -10 DAY);
SELECT ADDDATE(CURDATE(), INTERVAL -3 MONTH);



-- SUBDATE(YYYY-MM-DD, INTERVAL NN INTERVAL) 
SELECT SUBDATE"2022-11-26", INTERVAL 10 DAY);

-- SUBDATE(CURDATE(), INTERVAL NN INTERVAL) 
SELECT SUBDATE(CURDATE(), INTERVAL 10 DAY);
SELECT SUBDATE(CURDATE(), INTERVAL 1 MONTH);


-- SUBDATE(CURDATE(), INTERVAL -NN INTERVAL)
-- this will move forward in time like ADDDATE
SELECT SUBDATE(CURDATE(), INTERVAL -10 DAY);
SELECT SUBDATE(CURDATE(), INTERVAL -3 MONTH);


-- WEEKDAY
SELECT WEEKDAY(CURDATE());

-- WEEDAY BOOLEAN, RETURNS 1 OR 0
SELECT WEEKDAY(CURDATE()) = 1;